### ISSUE TITLE
qBit direct path / non-automanaged injection

### ISSUE THREAD

**Issue by argonan0** [jlw4049/BHDStudio-Upload-Tool#132]
**Is your feature request related to a problem? Please describe.**
The injection doesn't use the source path and requires a re-target & re-check if it's in a sub-folder of the category folder.

**Describe the solution you'd like**
The qBit injection ought to respect the MP4 location and use that for injection.
The qBit setting for automatic category management should be respected. (if it's disabled, do not enable for injected torrents)

Added bonus: the tool could have an option to move them from a flat directory into the named folder "This Movie (1234)" for Radarr compatibility.

**Describe alternatives you've considered**
The alternative is to have all MP4's in a flat directory. (not in individual folders)

**Additional context**
N/A

**Comment by jlw4049** [comment]
I'll keep this issue up and when I have some time I'll look at the direct injection again. Right now direct injection **should** work if you untick the **Remote** box in qBittorrent injection settings window. Have you tried to see if this works? If all of your torrents are local this should inject for 720/1080/4k just fine. 

Let me know

**Comment by jlw4049** [comment]
Keep me updated

**Comment by jlw4049** [comment]
Going to close this soon. Let me know if we need to work on any further changes and we can re open it and prioritize them.

If it's just multi cagetegory support based on resolution I think it would be acceptable.
