### ISSUE TITLE
Option to clear generated files on post

### ISSUE THREAD

**Issue by argonan0** [jlw4049/BHDStudio-Upload-Tool#133]
**Is your feature request related to a problem? Please describe.**
After an upload, generated files/folders are left in the encode file directory. These would get manually removed at some point.

**Describe the solution you'd like**
A checkbox on Upload that clears generated files/folders.

**Describe alternatives you've considered**
So long as the upload & injection is successful, these generated files are no longer necessary.

**Additional context**
![image](https://user-images.githubusercontent.com/101281012/234053968-be6dc9a8-7601-4857-ab64-5a74a01d4655.png)

**Comment by jlw4049** [comment]
I'll try to get this in before next release
