### ISSUE TITLE
Allow dupe link to be copied to clipboard

### ISSUE THREAD

**Issue by argonan0** [jlw4049/BHDStudio-Upload-Tool#149]
This is for the 4k trump channel. A button that posts a webhook call to the channel would also be a nice touch.

As it is now the dupe link is un-selectable so must be clicked to copy.

**Comment by jlw4049** [comment]
https://github.com/jlw4049/BHDStudio-Upload-Tool/commit/5a6647c8006f48a853886ba1fd05781af3677369

**Comment by jlw4049** [comment]
It does work, but you have to actually click it in the top list box FIRST and then the link appears. This is not really ideal from a flow perspective, I'll see how difficult it is to automatically select the top most option in the box upon opening the window.

**Comment by jlw4049** [comment]
I'm going to auto select the first option in the box before next patch
