### ISSUE TITLE
Image Viewer, hold shift and arrow key to move sets of images over

### ISSUE THREAD

**Issue by TJTurner8372** [jlw4049/BHDStudio-Upload-Tool#83]
I'd like a hot key to quickly move the chosen sets of photos over to the selected image list box

**Comment by jlw4049** [comment]
https://github.com/jlw4049/BHDStudio-Upload-Tool/commit/f0f60a9485ffb3fc1c714a2c0110a359e4b0c2f1

Completed, you can now utilize 
**Shift + Up Arrow Key** when using the image viewer window to load the current images to the selected image box
**Shift + Down Arrow Key** to undo the last loaded images in order
